name: activerecord-trino-adapter

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@4143b5fd2df506221b14b7bb334f680af37dbd64 # main
    with:
      package: ${{ github.workflow }}
      workdir: .
      gemfiles: "['gemfiles/rails_7_1.gemfile','gemfiles/rails_7_2.gemfile','gemfiles/rails_8_0.gemfile']"
      ruby: '["3.3"]'
    secrets: inherit
